name: Generate Contribution Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Snake Animation
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/snake.svg
            assets/snake-dark.svg?palette=github-dark
            
      - name: Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update contribution snake"
            git push
          fi
