name: Progress Bar Updater

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Update README.md with progress bar
        run: python progress_bar.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_user_name: "github-actions[bot]"
          commit_message: "docs(bar): Update README with progress bar"
