name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
          COMMIT_USERNAME: "github-actions[bot]"
          COMMIT_MESSAGE: "docs(waka): Update README with WakaTime stats"
          SHOW_PROFILE_VIEWS: false
          SHOW_TIMEZONE: false
